[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
assignment_5 = "64g726xowh1knCHgZyVsCEcymutxoa4yBcaLTczVzzxQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
